# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -gcflags \"all=-N -l\" -o reader_app ./cmd/reader_app/main.go"
bin = "./reader_app"
log = "./tmp/air_errors.log"

include_ext = ["go", "yaml", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "swagger"]
follow_symlink = true
exclude_regex = ["_test\\.go"]

delay = 100 # ms
kill_delay = 0 # ms
stop_on_error = true
send_interrupt = true
rerun = true
rerun_delay = 500

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true