version: '3.9'
services:
  app:
    container_name: app
    build: .
    env_file: .env
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./:/interview
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      external-interview-net:
        ipv4_address: 172.28.1.2
        aliases:
          - iapi

  mysql:
    container_name: mysql
    image: mysql
    env_file: .env
    volumes:
      - ./build/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "${MYSQL_NAME}"
      MYSQL_USER: "interview"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_TCP_PORT: "${MYSQL_PORT}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      external-interview-net:
        ipv4_address: 172.28.1.3
        aliases:
          - imysql

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass interview
    volumes:
      - cache:/data
    networks:
      external-interview-net:
        ipv4_address: 172.28.1.5
        aliases:
          - icache

  postgres:
    container_name: postgres
    image: postgres
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'interview'
      POSTGRES_PASSWORD: 'interview'
      POSTGRES_DB: 'interview'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U interview -d interview" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      external-interview-net:
        ipv4_address: 172.28.1.6
        aliases:
          - ipostgress

volumes:
  cache:
    driver: local
  pg-data:

networks:
  external-interview-net:
    external: true

#networks:
#  interview_net:
#    external: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.1.0/24