version: '3.9'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8081:8081"
    command: [ "sh", "-c", "/interview/bin/api" ]
    restart: always

  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: "${MYSQL_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: