swagger: "2.0"
info:
    description: example of golang features knowledge
    title: Interview application
    version: 1.0.0
schemes:
    - http
basePath: /api/v1
consumes:
    - application/json
produces:
    - application/json
paths:
    /user:
        get:
            description: Get user details
            operationId: getUser
            responses:
                "200":
                    $ref: '#/responses/User'
                "404":
                    $ref: '#/responses/NotFoundError'
            security:
                - apiKey:
                      - '[]'

definitions:
    item:
        type: object
        required:
            - description
        properties:
            id:
                type: integer
                format: int64
                readOnly: true
            description:
                type: string
                minLength: 1
            completed:
                type: boolean
securityDefinitions:
    key:
        type: apiKey
        in: header
        name: x-token