definitions:
  httpErrors
    NotFoundError:
        properties:
            code:
                format: int32
                type: integer
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
        type: object
        x-go-name: NotFoundResponse
        x-go-package: github.com/RafalSalwa/interview-app-srv/api/resource/responses
    User:
        properties:
            AuthToken:
                type: string
                x-go-name: JwtToken
            devices:
                items:
                    $ref: '#/definitions/UserDevice'
                type: array
                x-go-name: Devices
            firebaseToken:
                type: string
                x-go-name: FirebaseToken
            firstname:
                type: string
                x-go-name: Firstname
            id:
                format: int64
                type: integer
                x-go-name: Id
            lastname:
                type: string
                x-go-name: Lastname
            password:
                type: string
                x-go-name: Password
            roles:
                items:
                    type: string
                type: array
                x-go-name: Roles
            rolesJson:
                type: string
                x-go-name: RolesJson
            username:
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/RafalSalwa/interview-app-srv/pkg/models
    UserDevice:
        properties:
            brand:
                type: string
                x-go-name: Brand
            createdAt:
                format: date-time
                type: string
                x-go-name: CreatedAt
            deletedAt:
                format: date-time
                type: string
                x-go-name: DeletedAt
            firebaseToken:
                type: string
                x-go-name: FirebaseToken
            id:
                format: int64
                type: integer
                x-go-name: Id
            lastLogin:
                format: date-time
                type: string
                x-go-name: LastLogin
            model:
                type: string
                x-go-name: Model
            osType:
                format: int64
                type: integer
                x-go-name: OsType
            sdkVersion:
                format: int64
                type: integer
                x-go-name: SdkVersion
            userId:
                format: int64
                type: integer
                x-go-name: UserId
        type: object
        x-go-package: github.com/RafalSalwa/interview-app-srv/pkg/models
    Users:
        properties:
            items:
                items:
                    $ref: '#/definitions/User'
                type: array
                x-go-name: Items
        type: object
        x-go-package: github.com/RafalSalwa/interview-app-srv/pkg/models
paths:
    /auth/signup:
        post:
            description: Create new Account
            operationId: Create Account
            responses:
                "200":
                    description: User
                    schema:
                        $ref: '#/definitions/User'
                "401":
                    description: NotFoundError
                    schema:
                        $ref: '#/definitions/NotFoundError'
            security:
                - apiKey:
                    - '[]'
swagger: "2.0"
