global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'api_gateway_microservice'
    static_configs:
      - targets: [ 'gateway:8011' ]

  - job_name: 'auth_microservice'
    static_configs:
      - targets: [ 'auth_service:8021' ]
  
  - job_name: 'users_microservice'
    static_configs:
      - targets: [ 'user_service:8031' ]
  
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: [ 'otel_collector:8889' ]