global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'api_gateway_microservice'
    static_configs:
      - targets: [ 'api_gateway:8011' ]