version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
  docker: circleci/docker@2.2.0
jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run:
          name: "Setup APP_WD"
          command: echo 'export APP_WD="$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)/resources"' >> $BASH_ENV
      - run:
          name: Fetch dependencies
          command: go mod download
      - run:
          name: Unit test
          command: | 
            make test_unit
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          
  build:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run:
          name: "go mod"
          command: "go mod download"
  
#  lint:
#    docker:
#      - image: golangci/golangci-lint:v1.54-alpine
#    steps:
#      - checkout
#      - run: golangci-lint run
  

workflows:
  build_lint_test:
    jobs:
      - build
#      - lint
      - test