name: Gateway

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o gateway ./cmd/gateway/main.go
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: make test_integration