name: SonarCloud analysis

on:
  push:
  pull_request:
    branches: [ "1.x" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  contents: read
  checks: write
  
jobs:
  Analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "1.22.x"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
      - name: Prepare analysis
        run: |
          make test_unit
          go vet -json ./... > go_vet.json
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          args:
            -Dsonar.projectKey=RafalSalwa_auth-api
            -Dsonar.organization=rafalsalwa
