name: "Static check"
on:
  push:
  pull_request:
    branches: [ "1.x" ]

jobs:
  staticcheck:
    name: "Static check"
    runs-on: "ubuntu-latest"
    continue-on-error: true
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: "1.22.x"
    - run: make test_unit
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
        install-go: false
        cache-key: "1.22.x"