name: "CI"
on: ["push", "pull_request"]

jobs:
  staticcheck:
    name: "Static check"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: "1.22.x"
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
        install-go: false
        cache-key: "1.22.x"