name: Tests Unit

on:
  push:
  pull_request:
    branches: [ "1.x" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      env:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: "Unit tests"
    steps:
      - uses: actions/checkout@v4

      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "1.22.x"

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o gateway ./cmd/gateway/main.go

      - name: Test
        run: make test_unit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.out
          flags: unittests